[package]
name = "rip-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rip"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
sysinfo = "0.32"
skim = "0.10"
nix = { version = "0.29", features = ["signal"] }
